# Generated by Django 4.1.3 on 2022-11-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пользователь'),
        ),
    ]
