# Generated by Django 4.1.3 on 2022-11-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_missing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата исчезновения'),
        ),
    ]
