# Generated by Django 4.1.3 on 2022-11-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_date_missing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date_missing',
            new_name='_date_to_trash',
        ),
        migrations.AddField(
            model_name='note',
            name='in_trash_can',
            field=models.BooleanField(default=False, verbose_name='В корзине'),
        ),
    ]
