# Generated by Django 4.1.3 on 2022-11-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_date_missing_note__date_to_trash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date_create',
            new_name='_date_create',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='date_update',
            new_name='_date_update',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='favourites',
            new_name='_favourites',
        ),
    ]
