# Generated by Django 4.1.3 on 2022-11-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='favourites',
            field=models.BooleanField(blank=True, default=False, verbose_name='Добавить в избранное'),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название заметки'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Текст заметки'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Пользователь'),
        ),
    ]
