# Generated by Django 4.1.3 on 2022-11-08 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_favourites_alter_note_name_alter_note_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
        migrations.AddField(
            model_name='note',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='note',
            name='lifetime',
            field=models.DateField(default='2000-01-01', verbose_name='Время жизни'),
        ),
    ]
