# Generated by Django 4.1.3 on 2022-11-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_rename_date_create_note__date_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='_favourites',
            new_name='favourites',
        ),
        migrations.RemoveField(
            model_name='note',
            name='_date_to_trash',
        ),
        migrations.RemoveField(
            model_name='note',
            name='in_trash_can',
        ),
        migrations.AddField(
            model_name='note',
            name='date_to_trash',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
    ]
