# Generated by Django 4.1.3 on 2022-11-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_rename__favourites_note_favourites_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='_date_create',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='_date_update',
            new_name='date_update',
        ),
    ]
