# Generated by Django 4.1.3 on 2022-11-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note_date_note_date_create_note_date_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='lifetime',
            field=models.DurationField(default='999999', verbose_name='Время жизни'),
        ),
    ]
