# Generated by Django 4.1.3 on 2022-11-08 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_note_lifetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='lifetime',
        ),
        migrations.AddField(
            model_name='note',
            name='life_time',
            field=models.DurationField(default=datetime.timedelta(days=36135), verbose_name='Время жизни'),
        ),
    ]
