# Generated by Django 4.1.3 on 2022-11-20 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('notes', '0007_alter_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
