# Generated by Django 4.1.3 on 2022-11-12 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_remove_note_lifetime_note_life_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='life_time',
        ),
        migrations.AddField(
            model_name='note',
            name='date_missing',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 30, 19, 30, 30, 30), verbose_name='Дата исчезновения'),
        ),
    ]
